# Generated by Django 5.0 on 2024-04-01 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id_c', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id_s', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.corporation')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id_v', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=30)),
                ('soft_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.software')),
            ],
        ),
    ]
